name: hello_flutter
description: flutter 学习项目

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 日期、条件选择器
  flutter_pickers: ^2.1.3
  # 去除网页 URL 中的 “#” (hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.2.0
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # oktoast 插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.1.5
  # Dio 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.4
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # Flutter 轮播图 https://github.com/lianyagang/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2  # flutter_swiper很久不维护，可以使用空安全版本：flutter_swiper_null_safety
  # 启动 URL 的插件（支持 Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.12
  # 图片选择器,系统相机拍照（支持 Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.8.4+2
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^1.1.0
  # WebView 插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.3.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.4
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.2.0
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^2.0.0-nullsafety.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.2.0
  # 格式化 String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.0.1
  # 扫码 https://github.com/juliuscanute/qr_code_scanner
  qr_code_scanner: 0.6.1
  # App Shortcuts https://github.com/flutter/plugins/tree/master/packages/quick_actions
  quick_actions: 0.6.0+7
  # 振动（支持 Web） https://github.com/benjamindean/flutter_vibration
  vibration: ^1.7.4-nullsafety.0
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 3.1.1
  # 改变桌面端窗口大小(MacOS/Linux/Windows) https://github.com/mix1009/desktop_window
  desktop_window: 0.4.0
  # 刮刮卡 https://github.com/vintage/scratcher
  scratcher: ^2.1.0
  # 动画效果 https://github.com/xvrh/lottie-flutter
  lottie: ^1.2.1
  # dialog 弹窗 https://github.com/YYFlutter/flutter-custom-dialog
  flutter_custom_dialog: ^1.2.0
  # ios 风格图标
  cupertino_icons: ^1.0.2
  # 汉字转拼音 https://github.com/flutterchina/lpinyin
  lpinyin: ^2.0.2
  # 图片浏览  https://github.com/bluefireteam/photo_view
  photo_view: ^0.13.0
  # 图表,柱状图 https://github.com/imaNNeoFighT/fl_chart
  fl_chart: ^0.40.5
  # 代码扫描
  flutter_lints: ^1.0.0
  # GetX 是 Flutter 上的一个轻量且强大的解决方案：高性能的状态管理、智能的依赖注入和便捷的路由管理。
  # https://github.com/jonataslaw/getx/blob/master/README.zh-cn.md
  get: ^4.5.1

# 依赖覆盖
dependency_overrides:
  #  common_utils 使用的是 decimal : 2.0.0 会编译失败,暂时用 1.5.0 覆盖掉
  decimal: ^1.5.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/